### ISSUE TITLE
(node:106467) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.

### ISSUE THREAD

**Issue by reynard80** [carlos8f/zenbot#2607]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 20.04
- **Zenbot version** (commit ref, or version): 8a5792a
- **Zenbot branch**: unstable
- **NodeJS version**: 10
- **Exact command to reproduce (include everything)**: ./zenbot.sh trade --paper
- **Did I make any changes to conf-sample.js?**: no

### Describe the problem
When starting zenbot, I get a DepreactionWarning about collection.save. Should I use an older version of mongodb?

### Source code / Error logs
`(node:106467) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.`

**Comment by DeviaVir** [comment]
Dupe of https://github.com/DeviaVir/zenbot/issues/2234 ?

**Comment by reynard80** [comment]
Yes, but that issue isn't about this message despite the title.

**Comment by mmdiego** [comment]
Duplicate of #1988 and is already fixed.

**Comment by grainz** [comment]
> Duplicate of #1988 and is already fixed.

the error above is not corrected in the fix you tagged.

**Comment by mmdiego** [comment]
I don't see any bug described here. It only mentions a Warning message that appears somewhere. It doesn't give any kind of details and it's the same message fixed in #1988.
@grainz  What are you talking about?

**Comment by grainz** [comment]
I meant to say the warning, not an error, posted above was not included in the ticket you tagged.
They are the same type of warnings that were fixed but the one posted above is not fixed.
What are you talking about @mmdiego ? You say this is a duplicate but it is not.

**Comment by Pistol-Peet** [comment]
I do receive these warnings as well. Not sure about the exact impact yet.
@james-ingold stated his fix "Replaces deprecated save calls in mongodb with replaceOne and insertOne." and it was merged into unstable end of Feb 2020. Unfortunately I do receive the warning still...
![image](https://user-images.githubusercontent.com/71960913/109509485-373d0000-7aa1-11eb-8e40-0f80b565db76.png)
Version details:
nodejs/unknown,now 14.16.0-deb-1nodesource1 amd64
mongodb/focal,now 1:3.6.9+really3.6.8+90~g8e540c0b6d-0ubuntu5 amd64
Ubuntu 20.04

Despite the mentioned versions on the documentaries, is there a up-to-date recommendation?

**Comment by mmdiego** [comment]
There is stilll one call to save() in trade.js that wasn't changed in the previous fix, that's why the message is still appearing.
However, it won't affect functionality until it become obsolete.
I'll fix it soon if I have some time.
